language: csharp
solution: HotelBookingTests.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore HotelBookingTests.sln
after_script:
  - nunit-console HotelBookingTests.dll